development:
  adapter: postgresql
  encoding: unicode
  database: riverboss_develop
  pool: 5
  username: postgres
  password: PostgreSQL

test:
  adapter: postgresql
  encoding: unicode
  database: riverboss_develop
  pool: 5
  username: postgres
  password: PostgreSQL
