development:
  adapter: postgresql
  encoding: unicode
  database: riverboss_develop
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: riverboss_develop
  pool: 5
  username:
  password:
